[package]
name = "COW"
version = "0.1.0"
authors = ["Sven Schmidt <svenschmidt75@googlemail.com>"]
edition = "2018"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[dependencies]
